  const updateSettings = (updater: (s: ResumeSettings) => ResumeSettings) => { remember(); store.updateSettings(updater); };
  const undo = () => { const previous = past.current.pop(); if (!previous) return; future.current = [{ data: store.data, settings: store.settings }, ...future.current.slice(0, 49)]; store.updateData(() => previous.data); store.updateSettings(() => previous.settings); };
  const redo = () => { const next = future.current.shift(); if (!next) return; past.current = [...past.current.slice(-49), { data: store.data, settings: store.settings }, ...past.current.slice(-49)]; store.updateData(() => next.data); store.updateSettings(() => next.settings); };

  if (!store.resumeId) return <div className="flex h-dvh items-center justify-center bg-neutral-50 text-sm text-neutral-400">Loading your resume…</div>;
  const fileName = `${(store.data.personalInfo.fullName || 'Resume').replace(/\s+/g, '_')}_Resume.pdf`;
  const editorProps = { data: store.data, settings: store.settings, updateData, updateSettings };

  return <div className="oe-monster-editor flex h-dvh min-w-0 flex-col overflow-hidden bg-neutral-100 text-neutral-950"><IdleLogout />
    <header className="flex h-[60px] min-w-0 shrink-0 items-center gap-2 border-b border-neutral-200 bg-white px-2.5 sm:gap-3 sm:px-5 no-print"><Link href="/dashboard" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-neutral-500 hover:bg-neutral-100" aria-label="Back"><ArrowLeft className="h-4 w-4" /></Link><div className="h-5 w-px shrink-0 bg-neutral-200" /><div className="min-w-0 flex-1 overflow-hidden"><input value={store.title} onChange={(e) => store.setTitle(e.target.value)} className="block w-full max-w-[360px] min-w-0 truncate bg-transparent text-sm font-bold outline-none" aria-label="Resume name" /><div className="truncate text-[10px] text-neutral-400">Orrica Edge Resume Builder</div></div><div className="shrink-0"><SaveIndicator status={store.saveStatus} /></div><div className="hidden shrink-0 items-center gap-1 md:flex"><button type="button" onClick={undo} className="rounded-lg p-2 text-neutral-500 hover:bg-neutral-100" title="Undo"><Undo2 className="h-4 w-4" /></button><button type="button" onClick={redo} className="rounded-lg p-2 text-neutral-500 hover:bg-neutral-100" title="Redo"><Redo2 className="h-4 w-4" /></button><div className="mx-1 h-5 w-px bg-neutral-200" /><button type="button" onClick={() => setMoreOpen((v) => !v)} className="flex items-center gap-1 rounded-lg px-2.5 py-2 text-xs font-semibold text-neutral-600 hover:bg-neutral-100">More options <ChevronDown className="h-3.5 w-3.5" /></button><div className="relative">{moreOpen && <div className="absolute right-0 top-10 z-50 w-52 rounded-xl border border-neutral-200 bg-white p-1.5 shadow-xl"><Link href="/dashboard" className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs hover:bg-neutral-50"><History className="h-3.5 w-3.5" />Back to dashboard</Link><button type="button" onClick={() => window.location.reload()} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs hover:bg-neutral-50"><RotateCcw className="h-3.5 w-3.5" />Reload saved version</button><Link href="/templates" className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs hover:bg-neutral-50"><LayoutGrid className="h-3.5 w-3.5" />Browse templates</Link></div>}</div><PrintButton resumeId={resumeId} /><DownloadButton resumeId={resumeId} fileName={fileName} /></div></header>
    {/* Desktop editor/preview must not render on mobile. Rendering both desktop and mobile editors caused duplicate form fields and page overflow. */}
    <div className="relative hidden min-h-0 min-w-0 flex-1 md:flex">
      <ToolRail tool={tool} onTool={setTool} />
      <ToolPanel tool={tool} props={editorProps} onClose={() => setTool(null)} />
      <main className="flex min-h-0 min-w-0 flex-1">
        <section className={`hidden w-[320px] shrink-0 border-r border-neutral-200 bg-white lg:block ${tool ? 'opacity-40 pointer-events-none' : ''}`}><ContentList active={activeSection} onSelect={setActiveSection} data={store.data} /></section>
        <section className={`min-h-0 min-w-0 flex-1 ${tool ? 'hidden xl:block' : ''}`} aria-label="Resume editor"><div className="h-full min-h-0 overflow-hidden"><EditorContent sectionKey={activeSection} {...editorProps} /></div></section>
        <section className="hidden min-h-0 min-w-0 flex-1 md:block" aria-label="Live resume preview"><PreviewPane data={store.data} settings={store.settings} activeSection="" /></section>
      </main>
    </div>
    <div className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden md:hidden"> <MobileTools tool={tool} onTool={setTool} /><div className="min-h-0 min-w-0 flex-1 overflow-y-auto overflow-x-hidden">{tool ? <div className="bg-white p-4 sm:p-5">{tool === 'templates' || tool === 'design' ? <DesignPanel {...editorProps} setTemplate={(template) => updateSettings((s) => ({ ...s, template }))} /> : tool === 'sections' ? <SectionManager settings={store.settings} updateSettings={updateSettings} /> : <SpellCheckPanel />}</div> : mobileView === 'preview' ? <PreviewPane data={store.data} settings={store.settings} /> : <EditorContent sectionKey={activeSection} {...editorProps} />}</div><nav className="grid shrink-0 grid-cols-3 border-t border-neutral-200 bg-white no-print" style={{ paddingBottom: 'env(safe-area-inset-bottom)' }}><button type="button" onClick={() => setMobileView('edit')} className={`flex min-h-[58px] flex-col items-center justify-center gap-1 text-[10px] font-semibold ${mobileView === 'edit' ? 'text-orange-600' : 'text-neutral-400'}`}><Pencil className="h-5 w-5" />Edit</button><button type="button" onClick={() => setMobileView('preview')} className={`flex min-h-[58px] flex-col items-center justify-center gap-1 text-[10px] font-semibold ${mobileView === 'preview' ? 'text-orange-600' : 'text-neutral-400'}`}><FileText className="h-5 w-5" />Preview</button><DownloadButton resumeId={resumeId} fileName={fileName} /></nav></div>
  </div>;
}