export interface SampleExperience {
  role: string;
  company: string;
  dates: string;
  detail: string;
}

export interface SampleResumeProfile {
  name: string;
  title: string;
  email: string;
  phone: string;
  location: string;
  linkedin: string;
  summary: string;
  experience: SampleExperience[];
  education: string;
  skills: string[];
  project: string;
  certification: string;
  languages: string;
}

export const SAMPLE_RESUMES: Record<string, SampleResumeProfile> = {
  'Fresher / Graduate': { name: 'Riya Sharma', title: 'Business Administration Graduate', email: 'riya.sharma@email.com', phone: '+91 98765 12034', location: 'Bengaluru, India', linkedin: 'linkedin.com/in/riyasharma', summary: 'Recent business administration graduate with internship experience in operations, customer research and reporting. Strong communication, analytical thinking and Microsoft Office skills with a practical, results-focused approach.', experience: [{ role: 'Operations Intern', company: 'BrightPath Services', dates: 'Jan 2025 — Jun 2025', detail: 'Prepared weekly reports, supported process documentation and helped reduce manual follow-ups by 18%.' }, { role: 'Marketing Intern', company: 'Campus Growth Lab', dates: 'Aug 2024 — Dec 2024', detail: 'Coordinated student campaigns, maintained lead sheets and contributed to a 22% increase in registrations.' }], education: 'BBA, University of Bengaluru · 2025 · 8.4 CGPA', skills: ['MS Excel', 'PowerPoint', 'Communication', 'Research', 'Reporting', 'Teamwork'], project: 'Customer Feedback Analysis — analyzed 500+ responses and presented improvement recommendations.', certification: 'Google Digital Marketing Fundamentals · 2025', languages: 'English · Hindi · Kannada' },
  'IT / Software / Technology': { name: 'Arjun Mehta', title: 'Software Engineer', email: 'arjun.mehta@email.com', phone: '+91 98210 44321', location: 'Pune, India', linkedin: 'linkedin.com/in/arjunmehta', summary: 'Software engineer with 4+ years of experience building reliable web applications using React, TypeScript and Node.js. Experienced in API design, cloud deployment, testing and performance optimization.', experience: [{ role: 'Software Engineer', company: 'NovaTech Systems', dates: '2022 — Present', detail: 'Built React and Node.js applications, reduced page load time by 34% and improved API reliability through automated testing.' }, { role: 'Junior Developer', company: 'CodeBridge Labs', dates: '2020 — 2022', detail: 'Delivered customer-facing features, integrated REST APIs and collaborated with product and QA teams across six releases.' }], education: 'B.Tech, Computer Science, Pune Institute of Technology · 2020', skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'PostgreSQL', 'Git'], project: 'Analytics Dashboard — built a role-based dashboard processing 2M+ monthly events.', certification: 'AWS Certified Cloud Practitioner · 2024', languages: 'English · Hindi · Marathi' },
  'BPO / Customer Support': { name: 'Priya Singh', title: 'Customer Support Executive', email: 'priya.singh@email.com', phone: '+91 98111 77882', location: 'Gurugram, India', linkedin: 'linkedin.com/in/priyasingh', summary: 'Customer support professional with 3+ years of international voice and digital support experience. Skilled in de-escalation, first-contact resolution, CRM workflows and quality-focused communication.', experience: [{ role: 'Senior Customer Support Executive', company: 'GlobalServe', dates: '2023 — Present', detail: 'Handled 60+ customer interactions per day while maintaining 94% CSAT and exceeding quality targets.' }, { role: 'Customer Support Executive', company: 'ConnectOne', dates: '2021 — 2023', detail: 'Resolved billing and account issues through voice and chat support with a 91% first-contact resolution rate.' }], education: 'Bachelor of Arts, Delhi University · 2021', skills: ['Customer Service', 'Voice Process', 'CRM', 'Conflict Resolution', 'Email Support', 'English Communication'], project: 'Knowledge Base Refresh — helped rewrite 120 support articles and reduced repeat contacts.', certification: 'Customer Experience Foundations · 2024', languages: 'English · Hindi · Punjabi' },
  'Finance / Accounting': { name: 'Rohan Kapoor', title: 'Financial Analyst', email: 'rohan.kapoor@email.com', phone: '+91 98100 66542', location: 'Mumbai, India', linkedin: 'linkedin.com/in/rohankapoor', summary: 'Finance professional with 5 years of experience in financial analysis, budgeting, management reporting and variance analysis. Strong Excel and Power BI skills with a focus on accurate, decision-ready reporting.', experience: [{ role: 'Financial Analyst', company: 'Meridian Finance', dates: '2021 — Present', detail: 'Owned monthly management reporting and reduced reporting turnaround from five days to two through automated models.' }, { role: 'Accounts Executive', company: 'Axis Business Services', dates: '2019 — 2021', detail: 'Managed reconciliations, invoice controls and month-end support across 40+ business accounts.' }], education: 'B.Com, University of Mumbai · 2019', skills: ['Financial Modeling', 'Excel', 'Power BI', 'Budgeting', 'Variance Analysis', 'Accounting'], project: 'Budget Forecast Model — built a rolling 12-month model used by five department heads.', certification: 'Microsoft Power BI Data Analyst · 2024', languages: 'English · Hindi · Marathi' },
  'Sales / Business Development': { name: 'Kabir Malhotra', title: 'Business Development Manager', email: 'kabir.malhotra@email.com', phone: '+91 98990 44321', location: 'New Delhi, India', linkedin: 'linkedin.com/in/kabirmalhotra', summary: 'Business development professional with 6+ years of experience growing B2B pipelines, managing strategic accounts and closing complex sales. Proven record of exceeding revenue targets through consultative selling.', experience: [{ role: 'Business Development Manager', company: 'ScalePoint', dates: '2022 — Present', detail: 'Grew qualified pipeline by 46% and closed enterprise contracts worth more than Rs. 4.2 crore in two years.' }, { role: 'Account Executive', company: 'MarketBridge', dates: '2019 — 2022', detail: 'Managed 80+ active accounts and finished above annual quota in three consecutive years.' }], education: 'MBA, Marketing, IMT Ghaziabad · 2019', skills: ['B2B Sales', 'Negotiation', 'CRM', 'Pipeline Management', 'Account Growth', 'Presentations'], project: 'Enterprise Expansion Playbook — created a sales framework that increased cross-sell conversion by 19%.', certification: 'HubSpot Sales Software Certification · 2025', languages: 'English · Hindi' },
  'Marketing / Digital Marketing': { name: 'Ananya Verma', title: 'Digital Marketing Specialist', email: 'ananya.verma@email.com', phone: '+91 98700 33441', location: 'Hyderabad, India', linkedin: 'linkedin.com/in/ananyaverma', summary: 'Digital marketer with 5 years of experience across SEO, paid campaigns, content strategy and lifecycle marketing. Combines creative storytelling with analytics to improve acquisition, engagement and conversion.', experience: [{ role: 'Digital Marketing Specialist', company: 'GrowthCraft', dates: '2022 — Present', detail: 'Increased organic traffic by 58% and improved paid campaign ROAS by 31% through testing, content and audience segmentation.' }, { role: 'SEO Executive', company: 'PixelReach', dates: '2020 — 2022', detail: 'Managed 70+ landing pages and delivered technical and content SEO improvements that lifted non-brand clicks by 44%.' }], education: 'MBA, Marketing, Osmania University · 2020', skills: ['SEO', 'Google Ads', 'Content Strategy', 'GA4', 'Email Marketing', 'Analytics'], project: 'Organic Growth Program — built a 12-month content cluster strategy that generated 18K additional monthly visits.', certification: 'Google Analytics Certification · 2025', languages: 'English · Hindi · Telugu' },
  'HR / Recruitment': { name: 'Meera Iyer', title: 'Talent Acquisition Specialist', email: 'meera.iyer@email.com', phone: '+91 98450 22314', location: 'Chennai, India', linkedin: 'linkedin.com/in/meera-iyer', summary: 'HR and talent acquisition specialist with 5 years of experience hiring across technology and business functions. Skilled in sourcing, stakeholder management, interview coordination and candidate experience.', experience: [{ role: 'Talent Acquisition Specialist', company: 'PeopleFirst Technologies', dates: '2022 — Present', detail: 'Closed 110+ positions annually across engineering, product and support teams while improving offer acceptance to 87%.' }, { role: 'Recruitment Executive', company: 'TalentWorks', dates: '2020 — 2022', detail: 'Built sourcing pipelines, coordinated interviews and reduced average time-to-hire by 21%.' }], education: 'MBA, Human Resources, Madras University · 2020', skills: ['Talent Acquisition', 'Sourcing', 'Interviewing', 'ATS', 'Stakeholder Management', 'HR Operations'], project: 'Campus Hiring Program — launched a structured graduate hiring process across eight partner colleges.', certification: 'LinkedIn Talent Solutions Recruiter Certification · 2024', languages: 'English · Hindi · Tamil' },
  'Operations / Administration': { name: 'Vikram Joshi', title: 'Operations Manager', email: 'vikram.joshi@email.com', phone: '+91 97970 11882', location: 'Jaipur, India', linkedin: 'linkedin.com/in/vikramjoshi', summary: 'Operations leader with 7 years of experience managing teams, service delivery, process improvement and business reporting. Known for improving efficiency through clear SOPs, metrics and cross-functional execution.', experience: [{ role: 'Operations Manager', company: 'CoreServe Solutions', dates: '2021 — Present', detail: 'Led a 45-member operations team and improved SLA adherence from 88% to 97% through workflow redesign and daily performance reviews.' }, { role: 'Operations Executive', company: 'PrimeDesk Services', dates: '2018 — 2021', detail: 'Managed vendor coordination, reporting and process documentation across three business units.' }], education: 'BBA, Rajasthan University · 2018', skills: ['Operations Management', 'SOPs', 'Excel', 'MIS Reporting', 'Team Leadership', 'Process Improvement'], project: 'SLA Improvement Program — redesigned escalation workflows and reduced overdue cases by 36%.', certification: 'Lean Six Sigma Yellow Belt · 2024', languages: 'English · Hindi' },
  'Healthcare / Medical': { name: 'Dr. Neha Patel', title: 'Healthcare Administrator', email: 'neha.patel@email.com', phone: '+91 98250 44127', location: 'Ahmedabad, India', linkedin: 'linkedin.com/in/nehapatel', summary: 'Healthcare administration professional with 6 years of experience coordinating clinical operations, patient services, compliance reporting and multidisciplinary teams in high-volume healthcare environments.', experience: [{ role: 'Healthcare Administrator', company: 'CityCare Hospital', dates: '2021 — Present', detail: 'Coordinated front-office, billing and patient-service operations while improving registration turnaround by 27%.' }, { role: 'Clinical Operations Coordinator', company: 'WellSpring Medical Centre', dates: '2018 — 2021', detail: 'Supported scheduling, records workflows and compliance reporting across multiple departments.' }], education: 'MBA, Hospital Administration, Gujarat University · 2018', skills: ['Healthcare Operations', 'Patient Services', 'Compliance', 'Scheduling', 'Team Coordination', 'Reporting'], project: 'Patient Flow Improvement — redesigned appointment handoffs and reduced waiting time by 22%.', certification: 'Healthcare Quality Management · 2024', languages: 'English · Hindi · Gujarati' },
  'Creative / Design': { name: 'Aarav Mehta', title: 'Senior UI/UX Designer', email: 'aarav.mehta@email.com', phone: '+91 98710 55214', location: 'Bengaluru, India', linkedin: 'linkedin.com/in/aaravmehta', summary: 'Product and UI/UX designer with 7 years of experience creating digital products, design systems and accessible user experiences. Strong across research, interaction design, prototyping and product collaboration.', experience: [{ role: 'Senior UI/UX Designer', company: 'Studio North', dates: '2021 — Present', detail: 'Led product design for web and mobile experiences, improving task completion by 28% through research-led redesigns.' }, { role: 'Product Designer', company: 'CraftWorks', dates: '2018 — 2021', detail: 'Designed end-to-end workflows and established a reusable component library used across four product teams.' }], education: 'B.Des, National Institute of Design · 2018', skills: ['Figma', 'Design Systems', 'UX Research', 'Prototyping', 'Accessibility', 'Product Strategy'], project: 'Design System 2.0 — created 120+ reusable components and reduced design delivery time by 32%.', certification: 'Google UX Design Certificate · 2023', languages: 'English · Hindi' },
  'Executive / Management': { name: 'Sanjay Kapoor', title: 'Senior Operations Director', email: 'sanjay.kapoor@email.com', phone: '+91 98100 77221', location: 'Gurugram, India', linkedin: 'linkedin.com/in/sanjaykapoor', summary: 'Strategic operations leader with 14+ years of experience scaling teams, improving service delivery and leading transformation across multi-site organizations. Strong record of building accountable teams and translating strategy into measurable outcomes.', experience: [{ role: 'Operations Director', company: 'Vertex Global', dates: '2020 — Present', detail: 'Led 300+ employees across five sites and delivered 18% annual operating-cost improvement while raising service quality scores.' }, { role: 'Senior Operations Manager', company: 'EnterpriseWorks', dates: '2014 — 2020', detail: 'Directed regional operations, vendor performance and transformation programs across multiple business lines.' }], education: 'MBA, Operations Management, IIM Indore · 2012', skills: ['Strategic Leadership', 'P&L', 'Transformation', 'Operations', 'People Leadership', 'Stakeholder Management'], project: 'Enterprise Transformation — delivered a multi-site operating model that reduced cycle time by 25%.', certification: 'Executive Leadership Program · 2023', languages: 'English · Hindi' },
  'Photo / Professional': { name: 'Kavya Nair', title: 'Client Services Manager', email: 'kavya.nair@email.com', phone: '+91 98950 44312', location: 'Mumbai, India', linkedin: 'linkedin.com/in/kavyanair', summary: 'Client-facing professional with 6 years of experience in customer success, relationship management and service operations. Known for clear communication, premium client experience and strong retention results.', experience: [{ role: 'Client Services Manager', company: 'Prime Hospitality Group', dates: '2021 — Present', detail: 'Managed strategic client relationships and improved renewal rate to 92% through proactive service reviews and issue resolution.' }, { role: 'Customer Success Executive', company: 'ServiceHub', dates: '2018 — 2021', detail: 'Supported a portfolio of 120+ customers and consistently exceeded satisfaction and retention targets.' }], education: 'BBA, St. Xavier’s College · 2018', skills: ['Client Management', 'Customer Success', 'Communication', 'Relationship Building', 'Service Operations', 'CRM'], project: 'Client Experience Program — introduced quarterly account reviews that improved retention by 14%.', certification: 'Customer Success Foundations · 2024', languages: 'English · Hindi · Malayalam' },
};

export function getSampleResume(category?: string): SampleResumeProfile {
  return SAMPLE_RESUMES[category ?? 'Fresher / Graduate'] ?? SAMPLE_RESUMES['Fresher / Graduate'];
}
